#!/usr/bin/env python3
#
#   File : sapy
#   Author : stefano prina <stethewwolf@null.net>
#


from sapy_modules.commands import CommandLine_Parser
from sapy_modules.core import LoggerFactory
import sapy_modules.core.db as db_iface

if __name__ == "__main__":
    # setup logging service
    logger = LoggerFactory.getLogger('sapy')

    # the app starts
    logger.debug('sapy start')

    clp = CommandLine_Parser()

    command_list = clp.parse()

    logger.debug('start run commands')
    for cmd in command_list :
        logger.debug('running command ' + str( cmd.__class__ ) )
        print('running command ' + str( cmd.__class__ ) )
        cmd.run()
    
    # close db connection
    db_iface.close()

    # the app ends
    logger.debug('sapy end')
